### ISSUE TITLE
Put PHP Sessions in Redis

### ISSUE THREAD

**Issue by MatthewVita** [GoTeamEpsilon/OpenEMR-AWS-Guide#10]

**Comment by ghost** [comment]
Not the same thing I know but the title for a second made me think of this [course from Egghead](https://egghead.io/courses/getting-started-with-elasticsearch?utm_source=drip&utm_medium=email&utm_content=learn-elasticsearch&__s=gotapmb5w9s48vpze9xr). It's free for the next week so I'll probably run through it tonight before I lose internet Thursday - Sunday (I'll have it in spots with phone though).

**Comment by MatthewVita** [comment]
Nice!

**Comment by MatthewVita** [comment]
Making progress! https://github.com/GoTeamEpsilon/OpenEMR-AWS-Guide/commit/d00556af0339f14a98ed465c5747ebbf9b8f682c

**Comment by MatthewVita** [comment]
YES, just found out that memcached is already installed:

```
[ec2-user@ip-172-31-67-241 ~]$ php --ini | grep mem
/etc/php-7.0.d/40-memcache.ini,
/etc/php-7.0.d/50-memcached.ini,
```

...now on to hooking it up via ebextensions and securing it:

https://serverfault.com/questions/543077/how-to-add-directives-to-php-ini-on-aws-elastic-beanstalk/546784
http://docs.aws.amazon.com/AmazonElastiCache/latest/UserGuide/GettingStarted.AuthorizeAccess.html

**Comment by MatthewVita** [comment]
FINALLY DONE: https://github.com/GoTeamEpsilon/OpenEMR-AWS-Guide/blob/master/Other/MRV_working_guide.MD#redis-sessions

w00t!
