### ISSUE TITLE
Security and Compliance Services

### ISSUE THREAD

**Issue by ghost** [GoTeamEpsilon/OpenEMR-AWS-Guide#15]
Will periodically update this issue with easy-to-understand explanations of the various security services in AWS that we will use (maybe move this into a wiki at some point??). If you look on AWS you can find these services under "Management Tools" and "Security, Identity, and Compliance".

[**Config**](https://aws.amazon.com/config/) - define rules that you want your account to meet and see very easily whether or not you meet them. AWS has some OOTB rules as well as custom rules you can write (plus you add on Lambda functions to do the evaluation if you want!!)

![image](https://cloud.githubusercontent.com/assets/3357202/25156668/9e910fd4-2461-11e7-9c07-44f3753ffe3b.png)

**Comment by MatthewVita** [comment]
This is great. Nice find!

I don't know about a Wiki though, shouldn't this just be a part of the setup steps?

**Comment by ghost** [comment]
Can't we have a wiki directly in this Github project? I have no idea if
that would be useful. I guess I imagined it as an appendix maybe? Maybe to
dive more deeply into other topics but that we don't want to put in the
guide because it would interrupt the flow? I wouldn't have suggested it but
it is built into the platform...

This suggestion should either 1). immediately seem helpful or 2). you've
never seen a Github project with a wiki and no one really uses this
function in which case we should table it :)

**Comment by MatthewVita** [comment]
@danielehrlich wikis are SUPER useful and I've seen very popular GH repos with wikis. I guess I was missing your point about it being for supplementary information. That makes sense.

The idea is that guide should be all "happy path" based, but you're right that users should be able to dive deeper into supplementary information such as various considerations at certain steps (cost considerations, security implications, alternate options, etc).

My bet is that most users are going to want to just run with the base solution and be able to change code/database tables around as they need to for their own purposes. For example, let's say that, for whatever reason, an OpenEMR user writes custom code that adds a new tab section to the program for custom links (perhaps they put a link in there to a 3rd party billing solution website). This code wouldn't be very useful to the upstream codebase so the user should be able to add in the corresponding JS/HTML/CSS/PHP code and redeploy to beanstalk. This information would be probably end up in the wiki, right?

**Comment by ghost** [comment]
OOooh okay I didn't even think of that use case. Yes something like that! We can add this in much later though / even in another version once we have a better idea.

**Comment by MatthewVita** [comment]
This work is covered in our new issue/task tracker at https://app.asana.com/0/346554951567668/list
