### ISSUE TITLE
Create Custom Linux AMI for Elastic Beanstalk

### ISSUE THREAD

**Issue by ghost** [GoTeamEpsilon/OpenEMR-AWS-Guide#17]
Here are the steps IMO. A lot could definitely have been left out though. Also Matt I put you on this because that 3rd step I'm not sure how it's going to work. How is Elastic Beanstalk going to know where to put the PHP app exactly? Stuff like that:
1. [Create custom AMI](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/creating-an-ami-ebs.html)
2. [Share AMI on the marketplace](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/sharingamis-intro.html). 
3. [Use the custom image as environment for Elastic Beanstalk](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features.customenv.html)

**NOTE: Looks like the base image has to be a specific Elastic Beanstalk AMI that's available in EC2 that you customize from?

> To create a custom AMI, launch an Elastic Beanstalk platform AMI in Amazon EC2, customize the software and configuration to your needs, and then stop the instance and save an AMI from it.

**Comment by MatthewVita** [comment]
Are we still doing this?

**Comment by ghost** [comment]
No not at all sorry this wasn't closed out previously. The platform isn't really there yet and the regular Amazon Linux AMI is auto-updated I found out, after much searching, by Amazon.
