### ISSUE TITLE
Sign up for OG-AWS Slack

### ISSUE THREAD

**Issue by ghost** [GoTeamEpsilon/OpenEMR-AWS-Guide#18]
Can you all sign up for this Slack group? They are really good: https://og-aws-slack.lexikon.io/

I get a lot of pushback because I'm from Oracle (oh no we destroyed Hudson which forced the community to create Jenkins which is in fact a lot better!), so it would help for some of our really tough questions.

**Comment by MatthewVita** [comment]
link?

**Comment by ghost** [comment]
Fixed!

**Comment by MatthewVita** [comment]
> really tough questions

So they don't mind fielding AWS questions there?

**Comment by ghost** [comment]
1. Remember that elasticsearch course I posted? It was terrible don't go
2. No they don't mind except for from Oracle people :(.  What the questions
channel for the next few days...you should see some good stuff come up
And also them take seriously as far as answering.

-- 
Daniel Ehrlich

From: Matthew Vita <notifications@github.com> <notifications@github.com>
Reply: GoTeamEpsilon/OpenEMR-AWS-Guide
<reply@reply.github.com>
<reply@reply.github.com>
Date: April 27, 2017 at 5:37:57 PM
To: GoTeamEpsilon/OpenEMR-AWS-Guide <openemr-aws-guide@noreply.github.com>
<openemr-aws-guide@noreply.github.com>
CC: Daniel Ehrlich <daniel.ehrlich1@gmail.com> <daniel.ehrlich1@gmail.com>,
Author <author@noreply.github.com> <author@noreply.github.com>
Subject:  Re: [GoTeamEpsilon/OpenEMR-AWS-Guide] Sign up for OG-AWS Slack
(#18)

really tough questions
