### ISSUE TITLE
Set up IAM Draft Guide (Step #1)

### ISSUE THREAD

**Issue by ghost** [GoTeamEpsilon/OpenEMR-AWS-Guide#19]
Set up a very manual step-by-step guide, just like Matt did for EFS. These will make it really easy to write the CloudFormation templates later.

This guide will include stuff like creating a non-root main account, turning on MFA, creating other users, and creating the KMS keys.

**Comment by MatthewVita** [comment]
w00t

**Comment by MatthewVita** [comment]
See what I checked in at the top here: https://github.com/GoTeamEpsilon/OpenEMR-AWS-Guide#-getting-started

Feel free to add more information or simply add stuff to the administration section for advanced IAM usage.

**Comment by MatthewVita** [comment]
This work is covered in our new issue/task tracker at https://app.asana.com/0/346554951567668/list
