### ISSUE TITLE
Set up networks and the necessary VPC security (Step #3)

### ISSUE THREAD

**Issue by ghost** [GoTeamEpsilon/OpenEMR-AWS-Guide#20]
Network security is composed of:

- Creating the VPC (you'll already have on by default for you though)
- Create subnets for each availability zone. Create separate subnet for Database.
- Configure route tables of subnets
- Attach ACLs to those subnets (security step!)
- Attach a Security Group to each of the instances (all instances can share the same SG or use different ones, unless it's the DB) (security step!)
- Creation of VPN Gateway (optional I guess? if we do this they will have to do some manually set-up on premise I believe...maybe we can just use SSL, which is covered in another issue)

I am going to leave this open for you guys. It's very important to know. I know most of this other than the VPN part, since VPCs is like 60% of the AWS test...

**Comment by MatthewVita** [comment]
Ths work is covered in our new issue/task tracker at https://app.asana.com/0/346554951567668/list

**Comment by MatthewVita** [comment]
This work is covered in our new issue/task tracker at https://app.asana.com/0/346554951567668/list
