### ISSUE TITLE
Add WAF and SSL Cert (Step #8)

### ISSUE THREAD

**Issue by ghost** [GoTeamEpsilon/OpenEMR-AWS-Guide#21]
WAF is Web Application Firewall...it's a Layer 7 firewall
 
You can get an SSL Cert from AWS so it should be pretty easy to automate that process too

**Comment by ghost** [comment]
@MatthewVita SSL certs are apparently....FREE....with AWS!!! Can't believe that. I took screenshots of the whole process, but I entered too much info. Turns out you just need to enter, for our example, "*.goteamepsilon.com" and then you are good to go. I'll redo these screenshots later. They will form the visual part of our guide, which I can't remember if we even said we need, but it will be super useful for my reference when creating those CloudFormation templates.

**Comment by MatthewVita** [comment]
This work is covered in our new issue/task tracker at https://app.asana.com/0/346554951567668/list
