### ISSUE TITLE
Look into Terraform, open source CloudFormation

### ISSUE THREAD

**Issue by ghost** [GoTeamEpsilon/OpenEMR-AWS-Guide#22]
https://www.terraform.io/

This seems like an OpenSource version of CloudFormation...and it works on multiple clouds and on-premise? This is a far off topic, and would be something down the road...but might be an alternative to K8S. Still wouldn't mind doing K8S since I need to know more about containers, but this is amazing and I didn't know about it until today.

Thank you to @thatyellow, our maybe-new-member who is my superstar colleague at Oracle for suggesting this :)
She has passed the AWS-SA-Associate as well.

**Comment by MatthewVita** [comment]
https://app.asana.com/0/346554951567708/list
