### ISSUE TITLE
Create and Harden RDS Instance

### ISSUE THREAD

**Issue by ghost** [GoTeamEpsilon/OpenEMR-AWS-Guide#23]
This will be the DB instance that OpenEMR uses to maintain it's basic operating and configuration data...it does not really store patient documents I believe.

How should you secure the RDS instance?
There is networking stuff that other issues will take care of...but is there anything else?
How is encryption handled?
How are the backups protected?
Should create roles for the EC2 instances to access the DB?
Are there any other weird IAM users we should have specifically for the DB?
Should we use SSL for connecting to the DB? Even if it's just the app server connecting behind the scenes to DB server?
How should the DB be accessed for maintenance? A Bastion instance? VPN? SSH?
Anything else?

End State Goal:
- Have a txt document that describes in steps, say 1-30 or something, exactly how to set up install and then secure an RDS instance. AWS will change so doesn't have to be exact exact...
- You can leave the network stuff (subnet, security groups, etc) blank for now or put that in if you want
- Eventually document will be used for a guide and then orchestration templates so keep that second point in mind :)

**Comment by MatthewVita** [comment]
https://app.asana.com/0/346554951567708/list
