### ISSUE TITLE
Notification Emails

### ISSUE THREAD

**Issue by MatthewVita** [GoTeamEpsilon/OpenEMR-AWS-Guide#25]
I was wrong... OpenEMR does have emailer support: http://open-emr.org/wiki/index.php/Sms_and_Email_Notification_Howtos

Very useful feature. I'd like to get version 1 of the guide of the door, so let's put this on version 2.

**Comment by ghost** [comment]
Do we need this? https://aws.amazon.com/documentation/ses/

Or does OpenEMR manage on its own?

**Comment by MatthewVita** [comment]
I've used SES before. It's very easy to use. However, we would have to change OpenEMR source code.

Let's look into various options...

**Comment by MatthewVita** [comment]
This is version 2 work, which will be done in asana!
