### ISSUE TITLE
Daniel's Schedule

### ISSUE THREAD

**Issue by ghost** [GoTeamEpsilon/OpenEMR-AWS-Guide#26]
By end of May at latest!!!!

1. Finish AWS Security Course
2. Determine the AWS Users We Need / Permissions They Need
3. Complete IAM Draft Guide (it's another issue)
4. Figure out how to do AWS Scripting (it's in the Certified Developer Course)
5. Either go onto next topic or actually write out CloudFormation Script for IAM

**Comment by ghost** [comment]
1. FINISHED

2. FINISHED

3. In-Progress
- Sign up for trial account
- Document with screenshots each step
- Write steps out
- Use for for later reference as well during CloudFormation scripting stage

**Comment by ghost** [comment]
SCREENSHOTS:

STEP 0: 
STEP 1: https://www.dropbox.com/s/wrhmyec31ijpfi9/Screenshot%202017-05-09%2017.53.11.png?dl=0

**Comment by MatthewVita** [comment]
> Who else needs an account?? Maybe other hospital IT ppl if it's a big place?

Just IT admins. OpenEMR users will be added by the admin user they are not related to OS or AWS user accounts.

**Comment by ghost** [comment]
Updated on Step #3 it will require a new trial account though which I'll create shortly. This process is surprisingly poorly-documented online.

**Comment by MatthewVita** [comment]
Trial account for AWS?

**Comment by MatthewVita** [comment]
This work is now covered in our new issue/task tracker: https://app.asana.com/0/346554951567668/346554951567668
