### ISSUE TITLE
Created "Nested Stack" for hospital-defined variables 

### ISSUE THREAD

**Issue by ghost** [GoTeamEpsilon/OpenEMR-AWS-Guide#28]
Check this out: https://aws.amazon.com/blogs/devops/use-nested-stacks-to-create-reusable-templates-and-support-role-specialization/

So a "nested stack" is what makes CloudFormation scripts really reusable. I haven't studied them in-depth yet, but these will be where the variables that need to be user-defined will be entered. I'm not sure exactly what these are going to be, but some things that come to mind might be:

- which region do you want?
- passwords for certain services
- ?
- ?
- ?

TASK: determine which variables need to be user defined  
NOTE: I might revise this as I learn more about CF but I like Github issues it shows progress and my thought patterns

**Comment by MatthewVita** [comment]
So if I'm understanding, you can "link" service configurations together with these?

**Comment by ghost** [comment]
My understanding as of now is there are two documents. There is your long launch document. And then there is your "config file" which would have all of these variables and be referenced by the long launch document.

But yeah you could have 12 different documents in a particular stack...almost like you have 12 different js files that all reference each other. Infrastructure becoming like code :)

**Comment by MatthewVita** [comment]
If I'm following you, it sounds like we want config files doing all of the work and instead of "long launch" documents, we'd want it to be very "short" at that point.

**Comment by MatthewVita** [comment]
This work is now covered in our new issue/task tracker: https://app.asana.com/0/346554951567668/346554951567668
