### ISSUE TITLE
Bash script out steps 18-20 of the Redis EC2 instance setup

### ISSUE THREAD

**Issue by MatthewVita** [GoTeamEpsilon/OpenEMR-AWS-Guide#30]
Bash script out step 18 - 20 of https://github.com/GoTeamEpsilon/OpenEMR-AWS-Guide/blob/master/Other/MRV_working_guide.MD#redis-sessions

It would be great if the user could just copy and execute a bash script. The tricky part in doing this is using Linux tooling (hint: grek, sed, sed) to find the `bind` statement and comment it out.

**Comment by MatthewVita** [comment]
@robertogagliotta this would be a great first task for you to work on! Hope you are comfortable with Bash!

**Comment by robertogagliotta** [comment]
Brainstorming Session Open

**Comment by MatthewVita** [comment]
Roberto,

Are you familiar with grep/sed/awk?

Thanks,
Matthew

**Comment by robertogagliotta** [comment]
Yes, I was cobol programmer on Unix systems for 5 years back on 2001,
In 2001 you probably were on High School.  :)

**Comment by robertogagliotta** [comment]
I have using $ terminal on my ubuntu servers for the last 5 yrs

**Comment by robertogagliotta** [comment]
Matthew.
Slacks said thath my email address robertogagliotta@gmail.com does not belong to any team. I need a invitation:
 Hello! You're receiving this email because your email address was entered into slack.com/get-started, under "Join an existing team." We searched for Slack teams you've already joined or are allowed to join using robertogagliotta@gmail.com, but we couldn’t find any teams for that address.

If you're looking for a specific team, you can try contacting your Team Administrator for an invitation

**Comment by MatthewVita** [comment]
> In 2001 you probably were on High School. :)

Yup, ha.

> Team Administrator for an invitation

I will try again.

**Comment by robertogagliotta** [comment]
I know you invited me before. I did create the account and test it ok. After that it did not work.
I got a new slack account. thanks

**Comment by robertogagliotta** [comment]
I completed steps 1 - 20 ; 
Pseudocode for the redish_install.sh:
#!/bin/bash
clear
sudo apt-get update -y && 
sudo vi /etc/redis/redis.conf
comment 127.0.0.1
sudo service redis-server restart

IF THE USER WAS ABLE TO DO STEPS 1 - 16, STEPS 17-19 WILL BE CAKE ....

What do you think ??

**Comment by MatthewVita** [comment]
Cool. Maybe try `sed -i -- 's/bind 127.0.0.1/#bind 127.0.0.1/g' /etc/redis/redis.conf` ?

(untested)

**Comment by robertogagliotta** [comment]
My point was that this script will not help to the purpose. sorry Matthew I will not spend more time on this.

**Comment by MatthewVita** [comment]
I see what you mean. It's quite simple for the user.

Thanks

**Comment by robertogagliotta** [comment]
Hi Matthew
Due to my tight schedule I can not continue being part of the Epsilon Team
at this time. I wish you all the best with your group.
Roberto

**Comment by MatthewVita** [comment]
@robertogagliotta, I understand. Thanks anyways.
