### ISSUE TITLE
Better Task and Project Management

### ISSUE THREAD

**Issue by ghost** [GoTeamEpsilon/OpenEMR-AWS-Guide#34]
I started using Asana with a friend. I realize we don't have a great task management (I hesitate to use the word "project" here).

I would like something, like Asana, where we can all of my tasks, all of XYZ person's tasks, and then maybe joint-mini-project tasks.

The real benefit here is that 1) It's easy for me to see what's my responsibility and what I'm working on and 2) There is a motivation aspect right to it. Issues describe problems, but tasks describe clear solutions / things that need to be done and made. 
Also it's cool that you can see that I "did stuff" even if that "stuff" didn't result in a commit or closing out an issue.

Questions:

1. How is task management done at your job Matt? Is it all via issue assignment?
2. Not really a question but...I'm going to look into creating this. I know specifically Asana integrates with Slack (without even requiring Zapier).

Asana and Github integration is actually possible via Zapier: https://zapier.com/zapbook/asana/github/
Example screenshot of Asana:
![image](https://cloud.githubusercontent.com/assets/3357202/26132406/b12f36ce-3a65-11e7-9ded-ce59a66d2f84.png)

**Comment by ghost** [comment]
I hate to add more software to the mix...I feel like your ability to customize the minimum amount of software to your specific needs is a skill needed more in this world...but I just noticed issues weren't cutting it and "Github Projects" in no way do this.

**Comment by MatthewVita** [comment]
> Asana

If you feel like this is a good solution, I'm fine with using it. All I ask is for some instructions on how to use it and an account invite :).

> How is task management done at your job Matt? Is it all via issue assignment?

It's a very formal Agile Scrum.

> we don't have a great task management

For what it's worth, I have been keeping this up to date:

![f](https://cloud.githubusercontent.com/assets/1715206/26150693/8ae3cada-3acd-11e7-85c6-4dbbfb7a8253.png)

----

As far as my opinion on this, here are two pictures to understand how I generally go about doing things:

- http://blog.itil.org/wp-content/uploads/2014/08/AgileManifesto.png
- https://twitter.com/MatthewVita/status/833664841239916544

**Comment by ghost** [comment]
Ok looks like I can create "notes" in projects that aren't necessarily tied to issues, which I like. I will start using this more.

I'm about to create the Asana Workspace though still. Part of the reason is I've noticed a lot of my work is research...but I get guilty feelings when I'm studying / researching because it's not "commiting to the repo". I want you all to see what I'm studying, and it will motivate me to study more / faster if I know it's being seen (and also to be more disciplined in my topic choice).

**Comment by MatthewVita** [comment]
This work is now covered in our new issue/task tracker: https://app.asana.com/0/346554951567668/346554951567668
