### ISSUE TITLE
Get OpenEMR code into AWS (Step #2)

### ISSUE THREAD

**Issue by ghost** [GoTeamEpsilon/OpenEMR-AWS-Guide#35]
So this will be interesting. After all the user stuff has been created, we need to somehow get a copy of the latest version of the PHP code into S3...then Beanstalk can use it (see below screenshot).

- Option $1: just upload the correct source code to our own public S3 bucket and let whoever use that...might eventually have to use API Gateway or something to limit the requests so we don't get spammed. EASY

- Option $2: use the cloudformation template to spin up a quick machine that runs a "wget command"...copies the data into S3...then deletes itself. HARD

- Option $3: UNKNOWN

![image](https://cloud.githubusercontent.com/assets/3357202/26268118/4869492c-3cb3-11e7-9066-5c9e94ebcf58.png)

**Comment by MatthewVita** [comment]
We can just have the user upload their deployments to beanstalk

**Comment by MatthewVita** [comment]
thoughts?

**Comment by ghost** [comment]
Wait through the web console? Aren't we trying to do all of this via CloudFormation automatically?

**Comment by MatthewVita** [comment]
I guess what I'm envisioning is the following for the setup:

1) Clone OpenEMR v5 onto your local machine (optionally check it into a private git somewhere)
2) Download our .ebextensions into it
3) Sign up with AWS
4) Run the CloudFormation scripts (maybe we'll have a step here to allow the user to replace certain variables... for instance, they maybe need a bigger database in multiple AZ)
5) Navigate to EBS and upload your zipped up version of OpenEMR v5

Whenever the user wishes to make code changes to OpenEMR (maybe they developed a special module or something), they can deploy it just like with the step 5 above.

**Comment by MatthewVita** [comment]
Does this make sense or am I missing something? I guess my thoughts are we don't want to abstract away OpenEMR code from the end user. It is important for them to know they are in control of the code and can tweak it to their liking. Their local copy (or whatever they checked into git) is what they can deploy to production.

**Comment by MatthewVita** [comment]
This work is now covered in our new issue/task tracker: https://app.asana.com/0/346554951567668/346554951567668
