### ISSUE TITLE
Determine strategy for hosting patient portal

### ISSUE THREAD

**Issue by MatthewVita** [GoTeamEpsilon/OpenEMR-AWS-Guide#4]
http://open-emr.org/wiki/index.php/Patient_Portal

I've never messed around with the portal. We need to make sure it works with our solution!

**Comment by ghost** [comment]
Ok thanks for making me aware of this. Lol this will be a big security thing to lockdown since if I was hacking in I would choose this way (since you can't really use IP restrictions like you could for say a hospital system).

Cool though that OpenEMR has something for patients as well.

**Comment by MatthewVita** [comment]
Probably out of scope for version 1

**Comment by MatthewVita** [comment]
This work is covered in our new issue/task tracker at https://app.asana.com/0/346554951567708/list
