### ISSUE TITLE
Identify AWS Services

### ISSUE THREAD

**Issue by MatthewVita** [GoTeamEpsilon/OpenEMR-AWS-Guide#6]
I am thinking Elastic Beanstalk, RDS, Route53, IAM, TurnKey CouchDB, Cloudwatch, CloudFormation, and SES... is this a good selection? Am I missing anything?

**Comment by ghost** [comment]
Other services we should probably have:
- Certificate Manager (makes deploying SSL and managing your certs easy)
- WAF (Layer 7 firewall)

Some nice-to-have-but-not-necessary services:
- Cloudtrail (audit trail of every api call made)
- Glacier (cold off-line storage, like tape, very cheap)

**Comment by ghost** [comment]
This is some of the info that CloudTrail gives you btw:

![image](https://cloud.githubusercontent.com/assets/3357202/24325468/71b85826-1167-11e7-8104-aa2951f513a7.png)

**Comment by MatthewVita** [comment]
Nice!

**Comment by MatthewVita** [comment]
For Glacier, would that be for document backups? Is it HIPPA friendly?

RDS does backups on its own... don't need Glacier for that, right?

**Comment by ghost** [comment]
Glacier would just be for long term retention, like a lot of documents, such as my university health records, are kept for 7 years. I can only imagine this being a US / Western Europe requirement.
So Glacier is not for backups, but it's for data you just can't delete but will probably never use. 

Also I don't know a lot about healthcare (although I try!), so if you're ever like "wtf are you saying Daniel no one does that in healthcare" just let me know...

If we used that CouchDB EC2 images...you would do backups by taking snapshots of the EBS volumes which then get sent to S3. You can then delete this or also tier them into Glacier (so after 30 days you delete the backup in S3 and then move it to Glacier, where you keep it forever or maybe delete it from even Glacier after 90 days).

[CouchDB-EBS Volume]--->S3 Snapshot--->Glacier--->Delete? 

RDS does backups as well to S3 like above.

**Comment by MatthewVita** [comment]
Thanks for the detailed answer. Although I do work in healthcare, I can't claim to know all of the fine print details of every regulation... however, my understanding is that it depends on where you live in terms of max retention times. I would say, if possible, we should keep every document for each patient around forever. While this may be a bit aggressive, having a centralized place that captures a patient's _entire_ medical history is rather important.

Maybe I'm naive, but can't we just write a [node cron job](https://github.com/kelektiv/node-cron) that [backs up CouchDB to S3](https://github.com/philip-morning/backup-couchdb-to-s3) every night (limiting the backup count to 3)?

Note that S3 file upload max size is 5TB... this is probably good enough as it stands, but we may want to [tar split the archive up with a 5TB max per tar](http://unix.stackexchange.com/a/61776).

**Comment by MatthewVita** [comment]
![image](https://cloud.githubusercontent.com/assets/1715206/25065855/e11233a8-21e4-11e7-9b44-62da66c33e48.png)
