### ISSUE TITLE
Create Pricing Guide For End Users To Determine Which Strategy Is Best

### ISSUE THREAD

**Issue by ghost** [GoTeamEpsilon/OpenEMR-AWS-Guide#8]
At some point we should have forecasted pricing guides so that organizations can make their own decisions. Like if you implement these services with this much data you will spend XYZ amount.

Also having different configuration "tiers" would be good as well:

- So the lowest tier would be for very poor world areas that just need the bootstrapped version, and probably don't have lots of end users accessing the system due to not everyone having internet. 
- Then made a "middle" tier for 2nd world countries, e.g. Eastern Europe. In these countries pricing is definitely still a  concern but they have very good internet so HA and security are going to be important.
- Then high tier which is everything you could possibly want...good for if you are going to an open-source system from a vendor-system and just saving so much money it's laughable to spend just $10 more a month on a firewall...

**Comment by ghost** [comment]
[http://calculator.s3.amazonaws.com/index.html](http://calculator.s3.amazonaws.com/index.html)

**Comment by MatthewVita** [comment]
BTW, I'm sure certain orgs are non profit... we can write up about the free tier and limits

**Comment by ghost** [comment]
I talked with a Google App Engine developer on Upwork. He told me that a lot of his buddies were using Google Cloud because in the developing world their free policies make a big difference (I think you always get 28 hours free of App Engine per month forever or something).

Now that Google has come out with an "always free" compute tier, we can show how to do it there too maybe. It would just be a box with a single linux image, and we could probably use Packer to make the image which I believe would allow for it to be deployed on both AWS, Google, and others.

**Comment by MatthewVita** [comment]
I see. However, I think there is a fundamental drawback with GCP for the developing world: regions.

Here's GCP regions: https://dab1nmslvvntp.cloudfront.net/wp-content/uploads/2016/09/1473645753google-server-locations-1024x686.jpg

Here's AWS regions: https://dab1nmslvvntp.cloudfront.net/wp-content/uploads/2016/09/1473645242Global_Infrastructure_global-infra_6.14-1024x581.png

**Comment by MatthewVita** [comment]
I think version 2 will solve this problem because if we use something like Kubernetes a user can hire/fire their cloud provider as needed.

**Comment by MatthewVita** [comment]
AWS is probably a good start though

**Comment by ghost** [comment]
Lol Matt I never saw these comments (I at one time filtered Github emails because I was getting bombarded need to remove that gmail filter).

HAHAHA your picture of GCP is pretty funny...good god even Oracle Cloud has more data centers than that. I feel like I've launched at least 1 more since then but even then...

**Comment by MatthewVita** [comment]
https://www.youtube.com/watch?v=CQeezCdF4mk

**Comment by MatthewVita** [comment]
Ths work is covered in our new issue/task tracker at https://app.asana.com/0/346554951567668/list
