### ISSUE TITLE
Make Sure Deployments Are HIPAA Certified

### ISSUE THREAD

**Issue by ghost** [GoTeamEpsilon/OpenEMR-AWS-Guide#9]
This will be important and I always had trouble understanding this at work.

BTW technically Elastic Beanstalk is not HIPAA certified, but on all the forums they are saying you just have to configure it a certain way and then it is, because the underlying services are HIPAA compliant.

[https://aws.amazon.com/compliance/hipaa-eligible-services-reference/](https://aws.amazon.com/compliance/hipaa-eligible-services-reference/)

**Comment by MatthewVita** [comment]
Yup, there are workarounds so that it is!

**Comment by MatthewVita** [comment]
This work is covered in our new issue/task tracker at https://app.asana.com/0/346554951567668/list
